/**
 * SEC-007: convert snarkjs `verification_key.json` into a Rust
 * `Groth16Verifyingkey` constant consumed by the Solana program.
 *
 * Mirrors Light Protocol's `parse_vk_to_rust.js` (groth16-solana 0.2.0)
 * against VeilPay's withdraw circuit VK, fixing `nr_pubinputs` to
 * `IC.length - 1` (IC[0] is the constant term, not a public input).
 *
 * Usage:
 *   node scripts/generate_verifying_key.js \
 *     ../circuits/build/verification_key.json \
 *     programs/veil_pool/src/verifying_key.rs
 */

const fs = require("fs");
const path = require("path");

// Prefer the circuits package's ffjavascript if present; fall back to a
// pure-JS big-endian conversion so this script stays dependency-light.
function leInt2Buff(n, size) {
  const buf = Buffer.alloc(size);
  let x = BigInt(n);
  for (let i = 0; i < size; i++) {
    buf[i] = Number(x & 0xffn);
    x >>= 8n;
  }
  return buf;
}

function unstringifyBigInts(o) {
  if (typeof o === "string" && /^\d+$/.test(o)) return BigInt(o);
  if (typeof o === "number") return BigInt(o);
  if (Array.isArray(o)) return o.map(unstringifyBigInts);
  if (o && typeof o === "object") {
    const r = {};
    for (const k of Object.keys(o)) r[k] = unstringifyBigInts(o[k]);
    return r;
  }
  return o;
}

function bytesToRustList(bytes, indent) {
  const pad = "\t".repeat(indent);
  // Emit as a single line of u8 literals for compact diffs.
  return pad + Array.from(bytes).join(", ");
}

function processG1(point) {
  // snarkjs projective G1: [x, y, z=1] — keep affine (x,y), BE 32 each.
  const x = leInt2Buff(point[0], 32).reverse();
  const y = leInt2Buff(point[1], 32).reverse();
  return Buffer.concat([x, y]);
}

function processG2(point) {
  // snarkjs G2: [[x0,x1],[y0,y1],[1,0]] — limb packing matches groth16-solana.
  const out = [];
  for (let j = 0; j < 2; j++) {
    const c0 = leInt2Buff(point[j][0], 32);
    const c1 = leInt2Buff(point[j][1], 32);
    const concat = Buffer.concat([c0, c1]).reverse();
    out.push(concat.slice(0, 32), concat.slice(32, 64));
  }
  return Buffer.concat(out);
}

function main() {
  const inputPath = process.argv[2];
  const outputPath = process.argv[3];
  if (!inputPath || !outputPath) {
    console.error(
      "Usage: node generate_verifying_key.js <verification_key.json> <out.rs>"
    );
    process.exit(1);
  }

  const raw = JSON.parse(fs.readFileSync(inputPath, "utf8"));
  const vk = unstringifyBigInts(raw);

  if (!Array.isArray(vk.IC) || vk.IC.length < 2) {
    throw new Error("verification_key.json IC must have IC0 + ≥1 public input");
  }

  const nrPub = vk.IC.length - 1;
  const alpha = processG1(vk.vk_alpha_1);
  const beta = processG2(vk.vk_beta_2);
  const gamma = processG2(vk.vk_gamma_2);
  const delta = processG2(vk.vk_delta_2);
  const ic = vk.IC.map(processG1);

  let s = "";
  s += "// @generated by scripts/generate_verifying_key.js — do not edit by hand.\n";
  s += "// Source: packages/circuits/build/verification_key.json (Withdraw circuit).\n";
  s += "// Public inputs (order is load-bearing): [merkleRoot, nullifierHash, recipient, amount]\n";
  s += "use groth16_solana::groth16::Groth16Verifyingkey;\n\n";
  s += "#[rustfmt::skip]\n";
  s += "pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {\n";
  s += `\tnr_pubinputs: ${nrPub},\n\n`;

  s += "\tvk_alpha_g1: [\n";
  s += bytesToRustList(alpha, 2) + ",\n";
  s += "\t],\n\n";

  s += "\tvk_beta_g2: [\n";
  s += bytesToRustList(beta, 2) + ",\n";
  s += "\t],\n\n";

  // Field name is intentionally misspelled in groth16-solana 0.2.0.
  s += "\tvk_gamme_g2: [\n";
  s += bytesToRustList(gamma, 2) + ",\n";
  s += "\t],\n\n";

  s += "\tvk_delta_g2: [\n";
  s += bytesToRustList(delta, 2) + ",\n";
  s += "\t],\n\n";

  s += "\tvk_ic: &[\n";
  for (const point of ic) {
    s += "\t\t[\n";
    s += bytesToRustList(point, 3) + ",\n";
    s += "\t\t],\n";
  }
  s += "\t],\n";
  s += "};\n";

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, s);
  console.log(
    `Wrote ${outputPath} (nr_pubinputs=${nrPub}, ic=${ic.length})`
  );
}

main();
