/**
 * VeilPay — Stellar Private Payments (SPP) contract config
 *
 * Testnet IDs come from the vendored Nethermind deployment:
 *   packages/vendor/spp/deployments/testnet/deployments.json
 *
 * Mainnet remains **fail-closed** unless a valid deployment manifest is supplied.
 * Callers must use
 * {@link getSppConfigForChain} / {@link assertSppEnabled} so mainnet never
 * silently hits testnet contracts or an empty deployment.
 *
 * @see plans/spp-phase0-findings.md
 * @see plans/stellar-spp-integration-plan.md §4
 */

/** On-chain + RPC surface for one SPP deployment (one network). */
export interface SppDeploymentConfig {
  /** Chain key in the consumer app. */
  chainKey: string;
  /** Human network label for UI / logs (never secrets). */
  network: 'testnet' | 'mainnet';
  /** Public deployment account used as the source for read-only simulations. */
  deployer: string;
  /** Public administrator account recorded in the deployment manifest. */
  admin: string;
  /** Horizon HTTP API base (balance / account reads). */
  horizonUrl: string;
  /** Soroban RPC base (pool events + contract invoke). */
  sorobanRpcUrl: string;
  /** Stellar network passphrase for signing. */
  networkPassphrase: string;
  /** Native XLM privacy pool contract id (C…). */
  poolId: string;
  /** Circom Groth16 verifier (BN254) contract id. */
  verifierId: string;
  /** ASP membership Merkle tree contract id. */
  aspMembershipId: string;
  /** ASP non-membership (exclusion) tree contract id. */
  aspNonMembershipId: string;
  /** Public-key registry (G… → note/enc keys) contract id. */
  registryId: string;
  /** Classic asset contract for native XLM on this network. */
  nativeTokenContractId: string;
  /** Explorer base for tx links. */
  explorerBaseUrl: string;
  /** First pool deployment ledger used for complete note/event recovery. */
  deploymentLedger: number;
  /** Maximum native XLM deposit in stroops, copied from the constructor. */
  maxDepositStroops: string;
}

/**
 * Live Nethermind testnet deployment (verified Phase 0).
 * Self-deploy only if these contracts age out of RPC event retention (~7d)
 * or lose admin funding.
 */
export const SPP_TESTNET: SppDeploymentConfig = {
  chainKey: 'stellar-testnet',
  network: 'testnet',
  deployer: 'GDF4BXPQY5N4BEO24UIHM4NVB62MW7HDWH7SVHKLVZAMLP5IIHCFQORC',
  admin: 'GDF4BXPQY5N4BEO24UIHM4NVB62MW7HDWH7SVHKLVZAMLP5IIHCFQORC',
  horizonUrl: 'https://horizon-testnet.stellar.org',
  sorobanRpcUrl: 'https://soroban-testnet.stellar.org',
  networkPassphrase: 'Test SDF Network ; September 2015',
  poolId: 'CDLGZULLAUAILSZKT23AK4GND2UTY76QH5VP5DFNDBICCGS77OHWRQTU',
  verifierId: 'CC6RRMS5NRFNVAC2FEJN4BJUJ677GSDY5ARMJQE55IUQXTAEMGRRINZ3',
  aspMembershipId: 'CAGEKSPTCJUXUWAS54U3UFYDJZS5JYHK4H3L5TKIW74JDKQYNTNM43X2',
  aspNonMembershipId: 'CCVKPO23U6NSYTLZKG765I2OJXJWMQVR4QPMC7V4ITBO6E5MLIVEJPO3',
  registryId: 'CDNNPMUJ6GV343MZZ7H6C6YHHTPWJODNHV3CJ7Z7VGMUEXYWS7RR2BDD',
  nativeTokenContractId: 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC',
  explorerBaseUrl: 'https://stellar.expert/explorer/testnet',
  deploymentLedger: 3754534,
  maxDepositStroops: '1000000000',
};

/**
 * A deployment manifest generated by packages/vendor/spp/deployments/scripts/deploy.sh.
 * Keep this type JSON-compatible so the public artifact can be copied into
 * release configuration without ever including deployer secrets or the VK.
 */
export interface SppDeploymentManifest {
  network: 'mainnet' | 'testnet';
  deployer: string;
  admin: string;
  asp_membership: string;
  asp_non_membership: string;
  verifier: string;
  public_key_registry: string;
  pools: Array<{
    poolContractId: string;
    tokenContractId: string;
    deploymentLedger: number;
    enabled: boolean;
    asset?: { kind?: string };
  }>;
  maxDepositStroops?: string;
}

const STELLAR_CONTRACT_ID_RE = /^C[A-Z2-7]{55}$/;
const STELLAR_ACCOUNT_ID_RE = /^G[A-Z2-7]{55}$/;
function isPositiveInteger(value: unknown): value is number {
  return typeof value === 'number' && Number.isSafeInteger(value) && value > 0;
}

/** Validate public deployment output before it can become executable config. */
export function validateSppDeploymentManifest(
  manifest: unknown,
  expectedNetwork: 'mainnet' | 'testnet' = 'mainnet'
): manifest is SppDeploymentManifest {
  if (!manifest || typeof manifest !== 'object') return false;
  const m = manifest as Partial<SppDeploymentManifest>;
  if (m.network !== expectedNetwork) return false;
  if (![m.deployer, m.admin].every((id) =>
    typeof id === 'string' && STELLAR_ACCOUNT_ID_RE.test(id)
  )) return false;
  if (![m.asp_membership, m.asp_non_membership, m.verifier, m.public_key_registry].every((id) =>
    typeof id === 'string' && STELLAR_CONTRACT_ID_RE.test(id)
  )) return false;
  if (!Array.isArray(m.pools) || m.pools.length === 0) return false;
  return m.pools.some((pool) =>
    Boolean(pool && pool.enabled &&
      typeof pool.poolContractId === 'string' && STELLAR_CONTRACT_ID_RE.test(pool.poolContractId) &&
      typeof pool.tokenContractId === 'string' && STELLAR_CONTRACT_ID_RE.test(pool.tokenContractId) &&
      isPositiveInteger(pool.deploymentLedger) &&
      (pool.asset?.kind === undefined || pool.asset.kind === 'native'))
  );
}

/** Build executable config only from a validated public Mainnet manifest. */
export function sppConfigFromMainnetManifest(
  manifest: unknown,
  options?: { sorobanRpcUrl?: string; deploymentLedger?: number; maxDepositStroops?: string }
): SppDeploymentConfig | null {
  if (!validateSppDeploymentManifest(manifest, 'mainnet')) return null;
  const m = manifest as SppDeploymentManifest;
  const pool = m.pools.find((p) => p.enabled && (p.asset?.kind === undefined || p.asset.kind === 'native'));
  if (!pool) return null;
  const deploymentLedger = options?.deploymentLedger ?? pool.deploymentLedger;
  const maxDepositStroops = options?.maxDepositStroops ?? m.maxDepositStroops ?? '1000000000';
  if (!isPositiveInteger(deploymentLedger) || !/^\d+$/.test(maxDepositStroops) || BigInt(maxDepositStroops) <= 0n) {
    return null;
  }
  return {
    chainKey: 'stellar',
    network: 'mainnet',
    deployer: m.deployer,
    admin: m.admin,
    horizonUrl: 'https://horizon.stellar.org',
    sorobanRpcUrl: options?.sorobanRpcUrl?.trim() || '',
    networkPassphrase: 'Public Global Stellar Network ; September 2015',
    poolId: pool.poolContractId,
    verifierId: m.verifier,
    aspMembershipId: m.asp_membership,
    aspNonMembershipId: m.asp_non_membership,
    registryId: m.public_key_registry,
    nativeTokenContractId: pool.tokenContractId,
    explorerBaseUrl: 'https://stellar.expert/explorer/public',
    deploymentLedger,
    maxDepositStroops,
  };
}

function readMainnetManifest(): unknown {
  const raw = process.env.EXPO_PUBLIC_SPP_MAINNET_MANIFEST;
  if (!raw?.trim()) return null;
  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

/**
 * Mainnet is null unless the release environment contains a valid public
 * deployment manifest and Soroban endpoint. Missing or malformed values keep
 * SPP disabled; they can never produce an executable placeholder config.
 */
export const SPP_MAINNET: SppDeploymentConfig | null = (() => {
  const sorobanRpcUrl = process.env.EXPO_PUBLIC_SPP_SOROBAN_RPC_URL?.trim();
  if (!sorobanRpcUrl) return null;
  return sppConfigFromMainnetManifest(readMainnetManifest(), { sorobanRpcUrl });
})();

/**
 * Chain keys that may expose SPP UI / client entry points.
 *
 * Callers must still resolve the chain through `getSppConfigForChain`; Mainnet
 * remains unavailable unless the manifest and RPC passed validation.
 */
export const SPP_ENABLED_CHAIN_KEYS = [
  'stellar-testnet',
  'stellar',
] as const;

export type SppEnabledChainKey = (typeof SPP_ENABLED_CHAIN_KEYS)[number];

/**
 * Returns SPP deployment config for a chain key, or `null` when SPP is not
 * available (non-Stellar or not yet configured).
 */
export function getSppConfigForChain(chainKey: string | null | undefined): SppDeploymentConfig | null {
  if (!chainKey) return null;
  if (chainKey === SPP_TESTNET.chainKey) return SPP_TESTNET;
  if (chainKey === 'stellar' && SPP_MAINNET) return SPP_MAINNET;
  return null;
}

/**
 * True when the active chain is allowed to use SPP product surfaces.
 * Mainnet Stellar returns false until a valid release manifest is present.
 */
export function isSppEnabledForChain(chainKey: string | null | undefined): boolean {
  return getSppConfigForChain(chainKey) !== null;
}

/** Maximum deposit in whole XLM for the configured chain. */
export function getMaxDepositXlm(chainKey: string | null | undefined): number | null {
  const config = getSppConfigForChain(chainKey);
  if (!config || !/^\d+$/.test(config.maxDepositStroops)) return null;
  return Number(config.maxDepositStroops) / 10_000_000;
}

/** Translate known pool contract errors without hiding unknown diagnostics. */
export function friendlySppContractError(
  message: string | null | undefined,
  options?: { maxDepositXlm?: number | null }
): string | null {
  if (!message) return null;
  const match = message.match(/#(\d+)/);
  if (!match) return null;
  switch (Number(match[1])) {
    case 6:
      return options?.maxDepositXlm
        ? `Deposit must be a smaller amount (up to ${options.maxDepositXlm} XLM per transaction).`
        : 'Deposit must be a smaller amount within the pool limit.';
    case 7:
      return 'Private payment proof is invalid.';
    case 9:
      return 'This private note was already spent.';
    case 11:
      return 'The private pool is not ready yet. Try again shortly.';
    default:
      return null;
  }
}

/** Optional archive/bootnode URL used for complete private-history recovery. */
export function getSppBootnodeUrl(config: SppDeploymentConfig): string | null {
  const env = process.env.EXPO_PUBLIC_SPP_BOOTNODE_URL?.trim();
  if (env) return env;
  return null;
}

/** Mainnet is strict by default; Testnet preserves the existing dogfood default. */
export function getSppAllowPartialSync(config: SppDeploymentConfig): boolean {
  if (config.network === 'mainnet') return false;
  const raw = process.env.EXPO_PUBLIC_SPP_ALLOW_PARTIAL_SYNC?.trim().toLowerCase();
  if (raw === 'true') return true;
  if (raw === 'false') return false;
  return config.network === 'testnet';
}

/**
 * Fail-closed preflight for SPP ops and UI.
 *
 * @throws Error with `code: 'SPP_NOT_ENABLED'` when the chain has no SPP config
 *   (including an unconfigured Mainnet build).
 */
export function assertSppEnabled(chainKey: string | null | undefined): SppDeploymentConfig {
  const config = getSppConfigForChain(chainKey);
  if (!config) {
    const err = new Error(
        `SPP is not configured for ${chainKey === 'stellar' ? 'Stellar mainnet' : `chain "${chainKey ?? 'unknown'}"`}. Complete the deployment and release gates, then try again.`
    );
    (err as Error & { code?: string }).code = 'SPP_NOT_ENABLED';
    throw err;
  }
  return config;
}

/** Explorer deep-link for a submitted Soroban/Horizon tx hash. */
export function sppTxExplorerUrl(config: SppDeploymentConfig, txHash: string): string {
  const hash = txHash.replace(/^0x/i, '');
  return `${config.explorerBaseUrl}/tx/${hash}`;
}
