/**
 * Pass 2 — Graphify refresh runner.
 *
 * Regenerates `d:\Veilpay\graphify-out\` (or whatever `graphifyOutDir` the
 * orchestrator points us at) and produces a structured
 * `GraphifyRefreshSummary` consumed by Pass 4 (Reporting). Every spawn goes
 * through `runCommand` so evidence and failure-capture invariants are
 * uniform with the rest of Pass 2 (Property 14).
 *
 * Implements:
 *   - Requirement 3.1: Run the Graphify_Pipeline against the workspace root.
 *   - Requirement 3.2: Verify regeneration of GRAPH_REPORT.md, graph.json,
 *     and manifest.json.
 *   - Requirement 3.3: When `wiki/index.md` exists, verify it regenerated.
 *   - Requirement 3.4: Parse the top three architectural observations
 *     verbatim from GRAPH_REPORT.md.
 *   - Requirement 3.5: Record the run timestamp in ISO 8601.
 *   - Requirement 3.6 / Property 14: failure_capture is non-null iff exit
 *     code is non-zero, with command, exit code, and the last 50 lines of
 *     output bounded by the `runCommand` harness.
 *
 * Cache-stale fallback:
 *   The Graphify CLI sometimes short-circuits a `graphify .` invocation
 *   when its on-disk cache thinks nothing changed, in which case
 *   `wiki/index.md` is left stale even though the command exits 0. We
 *   detect this by comparing `wiki/index.md`'s mtime against the
 *   pre-spawn timestamp; if stale we re-run with `--update` to force a
 *   full rebuild (this matches the workspace `AGENTS.md` Graphify
 *   guidance: "If the graph is missing or stale, run `graphify .` or
 *   `graphify --update` first.").
 */

import { promises as fs } from 'node:fs';
import * as path from 'node:path';

import type {
  FailureCapture,
  GraphifyRefreshSummary,
} from '../../models';

import { MAX_TAIL_LINES, runCommand, type EvidenceRecord } from './runner';

/**
 * Sentinel inserted into `top_observations` when GRAPH_REPORT.md does not
 * yield enough parseable bullet/observation lines to fill the required
 * 3-tuple (Requirement 3.4). The literal is part of the contract with the
 * Pass 4 renderer so reviewers can immediately spot a thin observations
 * section without reading the raw Graphify output.
 */
export const OBSERVATION_NOT_PRESENT = 'observation not present' as const;

/**
 * Inputs required by `runGraphify`. Everything is an absolute path so the
 * runner does not have to guess about working directories.
 */
export interface RunGraphifyInput {
  /** Absolute path to the workspace root, e.g., `d:\Veilpay`. */
  readonly workspaceRoot: string;
  /** Absolute path to the Graphify output directory, e.g., `d:\Veilpay\graphify-out`. */
  readonly graphifyOutDir: string;
  /**
   * Absolute path to the Pass 2 evidence directory, typically
   * `d:\Veilpay\plans\.audit-evidence`. The graphify run's combined output
   * is written to `<evidenceDir>\graphify.txt` (and, on fallback, also
   * `<evidenceDir>\graphify-update.txt`) by `runCommand`.
   */
  readonly evidenceDir: string;
}

/**
 * Run Graphify and assemble the summary section consumed by Pass 4.
 *
 * The high-level flow:
 *   1. Capture `runStartedAt` *before* spawning so freshness checks have a
 *      monotonic floor.
 *   2. Run `graphify .` from `workspaceRoot` via `runCommand`.
 *   3. If exit code is non-zero OR `wiki/index.md` exists but its mtime is
 *      older than `runStartedAt`, fall back to `graphify --update`.
 *   4. On success, verify GRAPH_REPORT.md / graph.json / manifest.json
 *      exist and have mtime ≥ `runStartedAt`. If `wiki/index.md` exists,
 *      verify it too.
 *   5. Parse the top three observations from GRAPH_REPORT.md, padding with
 *      `OBSERVATION_NOT_PRESENT` when fewer than three exist.
 *   6. Build the `GraphifyRefreshSummary`. `failure_capture` is non-null
 *      iff the final invocation exited non-zero.
 *
 * On final-invocation failure the function does NOT throw; it returns a
 * summary whose `failure_capture` is populated and whose `top_observations`
 * is filled with `OBSERVATION_NOT_PRESENT` so the report renderer can still
 * emit a stable section. Callers (Pass 4) decide how to surface that to
 * the report verdict.
 */
export async function runGraphify(
  input: RunGraphifyInput,
): Promise<GraphifyRefreshSummary> {
  const { workspaceRoot, graphifyOutDir, evidenceDir } = input;

  // Floor for "fresh enough to count as regenerated by this run". Captured
  // before any spawn so we never accept a file that pre-existed unchanged.
  const runStartedAt = new Date();
  // Truncate the floor down by one millisecond. Some filesystems (notably
  // FAT-derived ones on Windows) round mtime to the nearest second, which
  // can cause a freshly-written file to report a timestamp slightly older
  // than the one we recorded immediately before spawning. The 1 ms slack
  // keeps the freshness check from rejecting such files.
  const freshnessFloor = runStartedAt.getTime() - 1000;

  const wikiIndexPath = path.join(graphifyOutDir, 'wiki', 'index.md');

  // ------------------------------------------------------------------
  // Step 2: graphify .
  // ------------------------------------------------------------------
  const primaryEvidence = path.join(evidenceDir, 'graphify.txt');
  const primary = await runCommand(
    'graphify',
    ['.'],
    primaryEvidence,
    { cwd: workspaceRoot },
  );

  // ------------------------------------------------------------------
  // Step 3: cache-stale or hard-failure fallback to graphify --update.
  // ------------------------------------------------------------------
  const wikiPresent = await pathExists(wikiIndexPath);
  const wikiStale =
    wikiPresent && !(await mtimeAtLeast(wikiIndexPath, freshnessFloor));
  const shouldFallback = primary.exitCode !== 0 || wikiStale;

  let finalRun: EvidenceRecord = primary;
  if (shouldFallback) {
    const fallbackEvidence = path.join(evidenceDir, 'graphify-update.txt');
    finalRun = await runCommand(
      'graphify',
      ['--update'],
      fallbackEvidence,
      { cwd: workspaceRoot },
    );
  }

  // The run timestamp recorded in the summary reflects when the *last*
  // invocation completed (or, more precisely, when the runner returned).
  // We use a fresh `new Date()` here per the task brief.
  const runAtIso = new Date().toISOString();

  // ------------------------------------------------------------------
  // Step 6 (early): hard failure on the final invocation.
  // ------------------------------------------------------------------
  // If the final invocation exited non-zero, populate failure_capture and
  // skip artifact verification + observation parsing — both would just
  // produce noise. The renderer needs a stable shape, so we still pad the
  // observations tuple with the sentinel.
  if (finalRun.exitCode !== 0) {
    return buildFailedSummary({
      finalRun,
      workspaceRoot,
      graphifyOutDir,
      runAtIso,
    });
  }

  // ------------------------------------------------------------------
  // Step 4: verify regeneration of required artifacts.
  // ------------------------------------------------------------------
  const requiredArtifacts: readonly string[] = [
    path.join(graphifyOutDir, 'GRAPH_REPORT.md'),
    path.join(graphifyOutDir, 'graph.json'),
    path.join(graphifyOutDir, 'manifest.json'),
  ];
  for (const artifactPath of requiredArtifacts) {
    await assertRegenerated(artifactPath, freshnessFloor);
  }
  if (await pathExists(wikiIndexPath)) {
    await assertRegenerated(wikiIndexPath, freshnessFloor);
  }

  // ------------------------------------------------------------------
  // Step 5: parse top three observations from GRAPH_REPORT.md.
  // ------------------------------------------------------------------
  const reportPath = path.join(graphifyOutDir, 'GRAPH_REPORT.md');
  const reportContents = await fs.readFile(reportPath, 'utf8');
  const observations = parseTopObservations(reportContents);

  return buildGraphifySummaryFromRecord(finalRun, {
    workspaceRoot,
    graphifyOutDir,
    runAtIso,
    observations,
  });
}

// =====================================================================
// Internal helpers
// =====================================================================

/**
 * Inputs accepted by `buildGraphifySummaryFromRecord` beyond the evidence
 * record itself. Splitting these out keeps the helper signature symmetric
 * for both the success and failure paths.
 */
export interface BuildGraphifySummaryArgs {
  /** Absolute path to the workspace root, e.g., `d:\Veilpay`. */
  readonly workspaceRoot: string;
  /** Absolute path to the Graphify output directory. */
  readonly graphifyOutDir: string;
  /** ISO 8601 timestamp recorded as `summary.run_at`. */
  readonly runAtIso: string;
  /**
   * Top three architectural observations parsed from GRAPH_REPORT.md. Used
   * only on the success path. When omitted, the 3-tuple is filled with
   * `OBSERVATION_NOT_PRESENT` so the renderer's section shape is stable.
   */
  readonly observations?: readonly [string, string, string];
}

/**
 * The minimal evidence-record shape consumed by
 * `buildGraphifySummaryFromRecord`. Mirrors the relevant fields of
 * `EvidenceRecord` so callers can construct synthetic records (e.g., from a
 * property-based test) without spawning a real process.
 */
export interface GraphifySummaryRecordLike {
  readonly command: string;
  readonly args: readonly string[];
  readonly exitCode: number;
  /** ISO 8601 timestamp captured at spawn time of the failing invocation. */
  readonly runAt: string;
  /**
   * Trailing combined-output lines. The runner caps this at
   * `MAX_TAIL_LINES`, but this builder defensively re-trims so the
   * resulting `failure_capture.output_tail` is guaranteed `<= 50` even when
   * a malicious caller passes a longer tail (Property 14, Invariant 2).
   */
  readonly tail: readonly string[];
}

/**
 * Pure function that converts a single graphify evidence record into the
 * `GraphifyRefreshSummary` consumed by the Pass 4 renderer.
 *
 * Property 14 contract:
 *   - Invariant 1: `failure_capture` is `null` iff `record.exitCode === 0`.
 *   - Invariant 2: when non-null, `failure_capture.output_tail.length <= 50`.
 *   - Invariant 3: when non-null, `failure_capture.exit_code === record.exitCode`.
 *
 * On success: emits `failure_capture: null` and uses the supplied
 * `observations` 3-tuple (or a sentinel-padded one if omitted).
 *
 * On failure: emits a `FailureCapture` with the command line, exit code,
 * defensively-trimmed output tail, and ISO 8601 `captured_at` timestamp.
 * `top_observations` is a sentinel-padded 3-tuple because the GRAPH_REPORT
 * either was not regenerated or could not be trusted.
 *
 * Factored out of `runGraphify` so the property test can validate the
 * shape contract without spawning the real `graphify` binary.
 */
export function buildGraphifySummaryFromRecord(
  record: GraphifySummaryRecordLike,
  args: BuildGraphifySummaryArgs,
): GraphifyRefreshSummary {
  const { workspaceRoot, graphifyOutDir, runAtIso, observations } = args;
  const graphReportLink = toRepoRelative(
    workspaceRoot,
    path.join(graphifyOutDir, 'GRAPH_REPORT.md'),
  );

  if (record.exitCode === 0) {
    const obs: readonly [string, string, string] = observations ?? [
      OBSERVATION_NOT_PRESENT,
      OBSERVATION_NOT_PRESENT,
      OBSERVATION_NOT_PRESENT,
    ];
    return {
      run_at: runAtIso,
      graph_report_link: graphReportLink,
      top_observations: obs,
      failure_capture: null,
    };
  }

  // exitCode !== 0 — defensively re-trim the tail so the shape contract
  // holds even if a caller hands us a record whose `tail` exceeds 50 lines.
  // The runner already enforces this cap, but Property 14 is about the
  // *summary builder's* output, not the runner's input.
  const tailTrimmed: readonly string[] =
    record.tail.length > MAX_TAIL_LINES
      ? record.tail.slice(record.tail.length - MAX_TAIL_LINES)
      : [...record.tail];

  const failure: FailureCapture = {
    command: formatCommand(record.command, record.args),
    exit_code: record.exitCode,
    output_tail: tailTrimmed,
    captured_at: record.runAt,
  };
  return {
    run_at: runAtIso,
    graph_report_link: graphReportLink,
    top_observations: [
      OBSERVATION_NOT_PRESENT,
      OBSERVATION_NOT_PRESENT,
      OBSERVATION_NOT_PRESENT,
    ],
    failure_capture: failure,
  };
}

/**
 * Build the summary returned when the final graphify invocation fails. Thin
 * wrapper around `buildGraphifySummaryFromRecord` retained so the call
 * site in `runGraphify` reads naturally.
 */
function buildFailedSummary(args: {
  readonly finalRun: EvidenceRecord;
  readonly workspaceRoot: string;
  readonly graphifyOutDir: string;
  readonly runAtIso: string;
}): GraphifyRefreshSummary {
  const { finalRun, workspaceRoot, graphifyOutDir, runAtIso } = args;
  return buildGraphifySummaryFromRecord(finalRun, {
    workspaceRoot,
    graphifyOutDir,
    runAtIso,
  });
}

/**
 * Render the failing command in a form a human can copy back into a
 * terminal. We stick to space-joined argv; the renderer wraps this in a
 * fenced code block so quoting is the reader's concern, not ours.
 */
function formatCommand(cmd: string, args: readonly string[]): string {
  return [cmd, ...args].join(' ');
}

/**
 * Return the path expressed relative to the workspace root, using POSIX
 * separators so the rendered Markdown link works regardless of the host
 * filesystem. Also strips a leading `./` if present.
 */
function toRepoRelative(workspaceRoot: string, target: string): string {
  const rel = path.relative(workspaceRoot, target);
  return rel.split(path.sep).join('/');
}

/** Resolve to true iff `target` exists on disk (file or directory). */
async function pathExists(target: string): Promise<boolean> {
  try {
    await fs.stat(target);
    return true;
  } catch (err) {
    if (isMissingFsError(err)) {
      return false;
    }
    throw err;
  }
}

/**
 * Resolve to true iff `target` exists and its mtime is at least
 * `floorMs` (epoch milliseconds). Missing files resolve to false rather
 * than throwing, so callers can treat "missing" and "stale" uniformly.
 */
async function mtimeAtLeast(target: string, floorMs: number): Promise<boolean> {
  try {
    const stats = await fs.stat(target);
    return stats.mtimeMs >= floorMs;
  } catch (err) {
    if (isMissingFsError(err)) {
      return false;
    }
    throw err;
  }
}

/**
 * Throw if `target` does not exist or its mtime is older than `floorMs`.
 * Used to verify that the final graphify invocation actually regenerated
 * each required artifact (Requirement 3.2 / 3.3). The thrown error message
 * is descriptive enough that the orchestrator can surface it directly.
 */
async function assertRegenerated(
  target: string,
  floorMs: number,
): Promise<void> {
  let stats;
  try {
    stats = await fs.stat(target);
  } catch (err) {
    if (isMissingFsError(err)) {
      throw new Error(
        `Graphify did not regenerate required artifact: ${target} (file missing).`,
      );
    }
    throw err;
  }
  if (stats.mtimeMs < floorMs) {
    throw new Error(
      `Graphify did not regenerate required artifact: ${target} ` +
        `(mtime ${new Date(stats.mtimeMs).toISOString()} ` +
        `older than run start ${new Date(floorMs).toISOString()}).`,
    );
  }
}

/** Narrowing helper: does this error look like ENOENT or similar? */
function isMissingFsError(err: unknown): boolean {
  if (typeof err !== 'object' || err === null) {
    return false;
  }
  const code = (err as NodeJS.ErrnoException).code;
  return code === 'ENOENT' || code === 'ENOTDIR';
}

/**
 * Parse the top three architectural observations from a GRAPH_REPORT.md
 * body. Per the task brief the heuristic is:
 *
 *   1. Find a section whose heading matches `## Observations` or
 *      `## Top Observations` (case-insensitive, optional `#` count of
 *      2 or more) and take the first three bullet list items
 *      (`- ...` / `* ...`) before the next heading.
 *   2. If no such section exists, fall back to the first three non-heading
 *      lines after the H1.
 *
 * Bullet markers and surrounding whitespace are stripped. If fewer than
 * three observations are recovered the result is padded with
 * `OBSERVATION_NOT_PRESENT` so the returned tuple always has cardinality
 * three (Requirement 3.4). Returned strings are exposed as a 3-tuple to
 * match `GraphifyRefreshSummary.top_observations`.
 */
export function parseTopObservations(
  reportContents: string,
): readonly [string, string, string] {
  const observations = collectObservations(reportContents);
  return [
    observations[0] ?? OBSERVATION_NOT_PRESENT,
    observations[1] ?? OBSERVATION_NOT_PRESENT,
    observations[2] ?? OBSERVATION_NOT_PRESENT,
  ];
}

/**
 * Heuristic extraction of up to three observations. Kept separate from
 * `parseTopObservations` so the padding rule lives in one obvious place.
 */
function collectObservations(reportContents: string): string[] {
  const lines = reportContents.split(/\r?\n/);

  // ---- Pass A: explicit Observations section ----------------------------
  const observationsHeadingIdx = lines.findIndex(isObservationsHeading);
  if (observationsHeadingIdx !== -1) {
    const fromHeading = lines.slice(observationsHeadingIdx + 1);
    const collected: string[] = [];
    for (const rawLine of fromHeading) {
      // Stop scanning when we hit the next Markdown heading.
      if (/^\s{0,3}#{1,6}\s/.test(rawLine)) {
        break;
      }
      const bulletText = stripBulletMarker(rawLine);
      if (bulletText !== null && bulletText.length > 0) {
        collected.push(bulletText);
        if (collected.length === 3) {
          break;
        }
      }
    }
    if (collected.length > 0) {
      return collected;
    }
    // Heading present but no bullets — fall through to Pass B so the
    // caller still gets *something* rather than three sentinels.
  }

  // ---- Pass B: first three non-heading lines after the H1 ---------------
  const h1Idx = lines.findIndex((line) => /^\s{0,3}#\s/.test(line));
  const startIdx = h1Idx === -1 ? 0 : h1Idx + 1;
  const collected: string[] = [];
  for (const rawLine of lines.slice(startIdx)) {
    if (/^\s{0,3}#{1,6}\s/.test(rawLine)) {
      // Skip nested headings entirely — they aren't observations.
      continue;
    }
    const stripped = stripBulletMarker(rawLine) ?? rawLine.trim();
    if (stripped.length === 0) {
      continue;
    }
    collected.push(stripped);
    if (collected.length === 3) {
      break;
    }
  }
  return collected;
}

/**
 * Match `## Observations` / `## Top Observations` and similar headings.
 * Allows 2..6 leading `#` characters and is case-insensitive.
 */
function isObservationsHeading(line: string): boolean {
  return /^\s{0,3}#{2,6}\s+(top\s+)?observations\s*$/i.test(line);
}

/**
 * If `line` is a Markdown bullet (`- ...` or `* ...`), return the text with
 * the marker and surrounding whitespace stripped. Otherwise return null.
 * The caller decides whether to substitute a fallback.
 */
function stripBulletMarker(line: string): string | null {
  const match = /^\s{0,3}[-*]\s+(.*)$/.exec(line);
  if (match === null) {
    return null;
  }
  // Index 1 is guaranteed to exist when the regex matches; the cast keeps
  // strict `noUncheckedIndexedAccess` happy without an extra runtime check.
  const text = (match[1] ?? '').trim();
  return text;
}
