// SPDX-License-Identifier: MIT
// AUTO-GENERATED. Do not edit manually. Regenerate via packages/circuits/compile.sh.
// Public inputs: [merkleRoot, nullifierHash, recipient, amount] — see design.md §Public input ordering contract
pragma solidity ^0.8.25;

import {IGroth16Verifier} from "./IGroth16Verifier.sol";

/**
 * @title Groth16Verifier
 * @notice Auto-generated by snarkjs from `packages/circuits/withdraw.circom`.
 *         The body of this file is overwritten on every successful run of
 *         `packages/circuits/compile.sh`. The compile script:
 *           1. Runs `snarkjs zkey export solidityverifier` into a temp file.
 *           2. Renames the generated `verifyProof(...)` to `_verifyProofRaw(...)`.
 *           3. Appends the wrapper from
 *              `packages/contracts-evm/src/Groth16VerifierWrapperTemplate.txt`
 *              so the contract conforms to {IGroth16Verifier}.
 *           4. Re-emits the canonical-ordering header comment above so the
 *              invariant survives every rebuild.
 *
 *         This file is currently the pre-compile stub: the wrapper is in
 *         place (declared `is IGroth16Verifier`) so downstream contracts
 *         (VeilPool, deploy script) can compile against the real ABI before
 *         the circuit is built. `verifyProof` returns `false` until
 *         compile.sh fills in the real pairing constants and `_verifyProofRaw`.
 */
contract Groth16Verifier is IGroth16Verifier {
    /// @inheritdoc IGroth16Verifier
    function verifyProof(
        bytes calldata,
        bytes32[] calldata
    ) external pure override returns (bool) {
        // Stub: real implementation injected by compile.sh post-processing.
        return false;
    }
}
