{
  "providers": [
    {
      "title": "NVIDIA NIM",
      "apiType": "openai",
      "apiKey": "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",
      "apiBase": "https://integrate.api.nvidia.com/v1"
    }
  ],
  "models": [
    {
      "title": "NVIDIA Llama 3.1 70B",
      "model": "meta/llama-3.1-70b-instruct",
      "apiType": "openai",
      "apiKey": "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",
      "apiBase": "https://integrate.api.nvidia.com/v1"
    },
    {
      "title": "NVIDIA DeepSeek R1",
      "model": "deepseek-ai/deepseek-r1",
      "apiType": "openai",
      "apiKey": "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",
      "apiBase": "https://integrate.api.nvidia.com/v1"
    }
  ]
}   